### ISSUE TITLE
the problem in using my own medical images for training 

### ISSUE THREAD

**Issue by chris1992212** [jmiller656/EDSR-Tensorflow#19]
hey, I have read and used your code for my own data. And my data is not easy to converge, So here is some questions about your code.  First, why do you remove the last convention after the up sampling?
Second, as I know, we often normalize our data in the range of 0 to 1, but in your code, the range is from 0 to 255. 
Thanks !

**Comment by jmiller656** [comment]
The last convolution seemed to cause problems for me empirically, so I ended up removing it. I believe I chose my normalization procedure for images based on what they did in the EDSR paper
