### ISSUE TITLE
How to enlarge the picture 4 double

### ISSUE THREAD

**Issue by woshizhangcheng** [jmiller656/EDSR-Tensorflow#23]
How to enlarge the picture 4 double

**Comment by nobody-cheng** [comment]
tf.train.latest_checkpoint(savedir) is None

**Comment by jmiller656** [comment]
There are a couple of ways you can do this:

1: train a model with argument `--scale 4`
2: train a 2x scale model and run on the image once, then again on the result (I don't recommend this)
