### ISSUE TITLE
ValueError: could not broadcast input array from shape (50,50,3) into shape (50,50)

### ISSUE THREAD

**Issue by cscyangj** [jmiller656/EDSR-Tensorflow#24]
Why this happen, do we need grey image?

>> python train.py --dataset train_600x600_to_800x800/data

where train_600x600_to_800x800/data is the image for training.

**Comment by PrathamSoni** [comment]
Your input file has three channels. If it is rgb or three channel grayscale u want to compress to one channel.

**Comment by cscyangj** [comment]
So if we need to processing RGB image, we need processing it per-channel?

**Comment by cscyangj** [comment]
It is okay when i use General_100, which is also RGB image, i think it is not related to gray image.

**Comment by PrathamSoni** [comment]
Ur images are inputting as three channel for some reason u might want to
check dimensions using numpy.

**Comment by cscyangj** [comment]
@PrathamSoni , thanks for your help.
