### ISSUE TITLE
Relu is not required out side the residual block

### ISSUE THREAD

**Issue by ZhenyF** [jmiller656/EDSR-Tensorflow#28]
Hi I read the paper and find out that the author did not implement Relu out side the residual block,
which means that **the first conv**, **convs in upsampling block** and **the conv after the upsampling** shouldn't followed by ReLU, but in your code it seems exist, could you please make a double check with that?
Also, may I know why do you disable the last conv layer after the upsampling block?
Please correct me if I make a mistake.

many thanks!

**Comment by mashoujiang** [comment]
Hi @ZhenyF , I think you can find the sampling code in [https://github.com/jmiller656/EDSR-Tensorflow/blob/master/model.py#L91](url), so the activation function is actually `None`, right?

**Comment by ZhenyF** [comment]
Hi @mashoujiang YUP! I just seen that. My bad...
