### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by CSlearn** [jmiller656/EDSR-Tensorflow#29]
File "E:\pycharm\mnist_tensorboard_test1\venv\Scripts\data.py", line 70, in get_test_set
    get_image(imgs[1], original_size)
IndexError: list index out of range

**Comment by MollyDai** [comment]
I have the same problem, and I cut my picture to a square， it works

**Comment by xiaojuan123** [comment]
在data.py中相应两行换成coords = [ (q,r) for q in range(int(coords_x)) for r in range(int(coords_y)) ]

	window = [x for x in range(int(counter*batch_size),int((counter+1)*batch_size))]
