### ISSUE TITLE
error in  train.py 

### ISSUE THREAD

**Issue by AsimSaif001** [jmiller656/EDSR-Tensorflow#36]
data.load_dataset(args.dataset,args.imgsize)
if args.imgsize % args.scale != 0:
    print("Image size "+{args.imgsize}+ " is not evenly divisible by scale" +{args.scale})
    return
what we have return nothing ?

**Comment by taniaCHY** [comment]
Begin training...
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    network.train(args.iterations,args.savedir)
  File "D:\Piao_Yi_Is_File\EDSR-Tensorflow-master\model.py", line 211, in train
    test_x,test_y = self.test_data(*self.test_args)
  File "D:\Piao_Yi_Is_File\EDSR-Tensorflow-master\data.py", line 67, in get_test_set
    get_image(imgs[0],original_size)
IndexError: list index out of range

**Comment by jmiller656** [comment]
@AsimSaif001 the error means you have an invalid configuration. We return because the program cannot continue with an invalid configuration

@taniaCHY try checking your image data directory. Chances are it doesn't exist or it is empty

**Comment by yuyifan1991** [comment]
@taniaCHY  Have you solved the problem? I have the same problem and I can't deal it.

**Comment by kong1060553768** [comment]
@yuyifan1991  @taniaCHY Just drop your SciPy to 1.2.1
