### ISSUE TITLE
What are the changes compared to the original paper?

### ISSUE THREAD

**Issue by jennyzu** [jmiller656/EDSR-Tensorflow#40]
Hi,

Thank you for the code.
Can you please elaborate on what are your changes compared to the original article? I didn't understand the explanation in the README.
I am trying to understand what to change in the code, if I want the same implementation as in the paper.

**Comment by luxuriance19** [comment]
> Hi,
> 
> Thank you for the code.
> Can you please elaborate on what are your changes compared to the original article? I didn't understand the explanation in the README.
> I am trying to understand what to change in the code, if I want the same implementation as in the paper.

I think the change of the implementation is the first layer, the paper is sub_mean of the div2k data set, 
and the upsampler layer is changed, in the paper, first pixshuffler then conv, here is first conv, then shuffler. but when I change the code into the orignal paper setting. The network can't converge. I think it's a little weird here. Do you have other implementations?

**Comment by jennyzu** [comment]
No, this is the only implementation I found. That's why it's important for me to understand the difference and understand why the difference exists.

**Comment by jmiller656** [comment]
Hey, here's a link to an implementation by the original author: https://github.com/LimBee/NTIRE201
