### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by ZJ1224** [jmiller656/EDSR-Tensorflow#43]
there is an error happened when running train.py

****************************************************************************
if args.imgsize % args.scale != 0:
    print("Image size "+{args.imgsize}+ " is not evenly divisible by scale" +{args.scale})
    return
****************************************************************************
 return
    ^
SyntaxError: 'return' outside function

**Comment by yuyifan1991** [comment]
@ZJ1224 Have you fixed the problem? I have the same isuues.

**Comment by jmiller656** [comment]
Can you tell me what version of python you're running and what your OS is? I'm not experiencing this problem. Looks like the indentation for the return is not showing up for some reason

**Comment by jmiller656** [comment]
Found the problem. Try cloning again, it should be fixed now
