### ISSUE TITLE
How to control the training epochs in the codes ?

### ISSUE THREAD

**Issue by sdlpkxd** [jmiller656/EDSR-Tensorflow#48]
Excuse me 
In the code we can control the loop by the parameter iterations, but how can we know how many epochs we trained ?
Thanks in advance

**Comment by kong1060553768** [comment]
Iterations are iterations, which are shown by tqdm! By the way, how was your training result?

**Comment by jmiller656** [comment]
My current data utilities don't calculate epochs based on your dataset size, so you'd have to do some math to carefully decide the number of training iterations instead.


This may be fixed in a future version where I switch the library to keras
