### ISSUE TITLE
2x scale photo without downscale

### ISSUE THREAD

**Issue by naseeresmael** [jmiller656/EDSR-Tensorflow#5]
Hi @jmiller656, thank you for your great work, i have some photo want to upscale it by 2x , but after i train the network and try to use it to scale my own photo to 2x , it downscaled and croped, could you please explan to me how can to train the network to upscal 2x dirctly , then how to use test.py to this target .

**Comment by jmiller656** [comment]
Hey, sorry about that! Please stay tuned, I plan on having this fixed within the next week.

**Comment by naseeresmael** [comment]
wow, that is really great news، i will be waiting for this update until you get some time to it, thank you 👍

**Comment by jmiller656** [comment]
@naseeresmael just wanted to notify you, I've submitted a fix for this issue. If you run into any more issues, feel free to reopen this issue or create a new one. Thanks!

**Comment by naseeresmael** [comment]
ok, thank you @jmiller656 For your efforts 👍👏

**Comment by naseeresmael** [comment]
hi @jmiller656, when i try to trining i found this error 
Done building!
Begin training...
  0%|
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    network.train(args.iterations,args.savedir)
  File "F:\EDSR\model.py", line 212, in train
    x,y = self.data(*self.args)
  File "F:\EDSR\data.py", line 66, in get_batch
    img = crop_center(img,original_size,original_size)
  File "F:\EDSR\data.py", line 81, in crop_center
    y,x,_ = img.shape
ValueError: not enough values to unpack (expected 3, got 2)

how can i fix that, sorry for wasting your time.
