### ISSUE TITLE
how to training MDSR

### ISSUE THREAD

**Issue by suke27** [jmiller656/EDSR-Tensorflow#52]
Hello, in case MDSR, we need training x2 x3 and x4 model one time.
could you help to point that, how to improve train code.

**Comment by suke27** [comment]
no body know about it?

**Comment by Saafke** [comment]
You can find MDSR code and a pre-trained MDSR model for TensorFlow in this repo: https://github.com/Saafke/EDSR_Tensorflow/tree/mdsr
